[versions]
# Plugins
kotlin = "1.9.25"
shadow = "8.3.0"
exposed = "0.54.0"
thrivi = "13199ef603"
dico = "f00e6003b3"
notchity = "8bf2b5125e"
postgresql = "42.7.4"
sqlite = "3.46.1.0"

[libraries]
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
thrivi = { module = "com.github.kvdpxne:thrivi", version.ref = "thrivi" }
dico-api = { module = "com.github.kvdpxne.dico:api", version.ref = "dico" }
dico-core = { module = "com.github.kvdpxne.dico:core", version.ref = "dico" }
notchity = { module = "com.github.kvdpxne:notchity", version.ref = "notchity" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[bundles]
disco = ["dico-api", "dico-core"]
exposed = ["exposed-core", "exposed-jdbc"]