[versions]
dico = "0.1.1"
dokka = "2.0.0"
exposed = "0.59.0"
kaml = "0.72.0"
kotlin = "2.1.10"
kotlinx-coroutines = "1.10.1"
kotlinx-serialization = "1.8.0"
notchity = "0.2.0"
postgresql = "42.7.5"
protocollib-current = "4.8.0"
protocollib-legacy = "3.7.0"
shadow = "8.3.6"
spigot-current-oldest = "1.8-R0.1-SNAPSHOT"
spigot-legacy = "1.7.2-R0.1-SNAPSHOT"
sqlite = "3.49.0.0"
thrivi = "13199ef603"

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
dico = { module = "com.github.kvdpxne.dico:core", version.ref = "dico" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
kotlinx-coroutines-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jvm", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }
notchity = { module = "com.github.kvdpxne.notchity:bukkit", version.ref = "notchity" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
protocollib-current = { module = "com.comphenix.protocol:ProtocolLib", version.ref = "protocollib-current" }
protocollib-legacy = { module = "com.comphenix.protocol:ProtocolLib-Legacy", version.ref = "protocollib-legacy" }
spigot-current-oldest = { module = "org.spigotmc:spigot-api", version.ref = "spigot-current-oldest" }
spigot-legacy = { module = "org.spigotmc:spigot-api", version.ref = "spigot-legacy" }
sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
thrivi = { module = "com.github.kvdpxne:thrivi", version.ref = "thrivi" }

[bundles]
exposed = ["exposed-core", "exposed-jdbc"]