name: "✨ Feature request"
description: "Suggest an idea for this project."
title: "[FEATURE]"
labels:
  - "enhancement"
body:
  - type: "textarea"
    attributes:
      label: "Describe your feature request."
      description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]."
    validations:
      required: true