package me.kvdpxne.dtm.raw

/**
 * Predefined collection of game names for automatic assignment.
 *
 * Contains 40 epic fantasy-themed game names generated by AI, featuring:
 * - Cosmic and elemental themes ("elemental_convergence", "voidtouched")
 * - Legendary battle concepts ("eternal_champions", "titanforged")
 * - Mystical locations ("nexus", "sanctum", "colosseum")
 *
 * ### Example Names
 * - "the_primordial_combat_collection"
 * - "the_voidwalker_trial_grounds"
 * - "the_celestial_warrior_series"
 *
 * @since 0.1.0
 */
val NAMES_OF_GAMES by lazy {
  arrayOf(
    "the_elemental_convergence",
    "the_eternal_champions_gauntlet",
    "the_trinity_of_eternal_strife",
    "the_celestial_trial_nexus",
    "the_grand_tournament_of_realms",
    "the_infinity_battle_sanctum",
    "the_chronos_arena_complex",
    "the_nexus_of_warring_spheres",
    "the_primordial_combat_collection",
    "the_legacy_of_shattered_worlds",
    "the_sovereigns_proving_grounds",
    "the_ascension_arena_cluster",
    "the_echoes_of_eternal_conflict",
    "the_godforged_battlefield_set",
    "the_dimension_weavers_colosseum",
    "the_wardens_eternal_challenge",
    "the_obsidian_circuit_of_legends",
    "the_conclave_of_shattered_stars",
    "the_aeon_warrior_sanctuary",
    "the_apocalypse_trilogy_arena",
    "the_voidwalker_trial_grounds",
    "the_dragonkings_sovereign_domain",
    "the_celestial_guardian_series",
    "the_infernal_pantheon_battlegrounds",
    "the_titanforged_combat_nexus",
    "the_equilibrium_of_warring_elements",
    "the_eternity_champion_collection",
    "the_archmage_grand_arena_set",
    "the_chronomancer_battle_sequence",
    "the_immortal_guardian_quadrilogy",
    "the_warden_gate_arena_sequence",
    "the_eternal_guardian_quartet",
    "the_sovereign_battle_domain_set",
    "the_apocalypse_proving_grounds",
    "the_cosmic_strife_trilogy",
    "the_voidtouched_arena_collection",
    "the_dragonfire_championship_circuit",
    "the_celestial_warrior_series",
    "the_elemental_conflux_arenas",
    "the_archon_eternal_battlegrounds"
  )
}

/**
 * Predefined collection of arena names for automatic assignment.
 *
 * Contains 50 diverse arena names generated by AI, featuring:
 * - Elemental environments ("fire_valley", "frost_peak")
 * - Fantasy locations ("sky_fortress", "ancient_tomb")
 * - Creature-themed arenas ("dragon_lair", "wyvern_nest")
 *
 * ### Example Names
 * - "obsidian_pinnacle"
 * - "mirage_oasis"
 * - "divine_forge"
 *
 * @since 0.1.0
 */
val NAMES_OF_ARENAS by lazy {
  arrayOf(
    "dragon_lair",
    "ice_kingdom",
    "fire_valley",
    "shadow_realm",
    "thunder_dome",
    "crystal_cave",
    "lava_pit",
    "sky_fortress",
    "dark_forest",
    "iron_arena",
    "mystic_grove",
    "sand_temple",
    "frost_peak",
    "emerald_field",
    "nether_core",
    "ocean_depth",
    "golden_gate",
    "storm_haven",
    "moon_garden",
    "ancient_tomb",
    "void_abyss",
    "sunken_citadel",
    "lightning_spire",
    "petrified_forest",
    "obsidian_pinnacle",
    "celestial_dome",
    "phantom_maze",
    "serpent_falls",
    "golem_forge",
    "tempest_harbor",
    "cursed_colosseum",
    "mirage_oasis",
    "specter_woods",
    "titan_peak",
    "venomous_marsh",
    "astral_nexus",
    "ruined_acropolis",
    "blight_canyon",
    "wyvern_nest",
    "sapphire_grotto",
    "inferno_core",
    "thunderkeep",
    "solar_spire",
    "ghost_ship",
    "coral_reef",
    "meteor_crater",
    "bone_charnel",
    "stormspire",
    "fungal_grotto",
    "clockwork_city",
    "dreamscape",
    "divine_forge"
  )
}

/**
 * Predefined collection of arena map names for automatic assignment.
 *
 * Contains 50 immersive map names generated by AI, featuring:
 * - Mystical locations ("forgotten_city", "enchanted_forest")
 * - Dramatic environments ("volcanic_crater", "bloodstone_caverns")
 * - Cosmic and temporal themes ("twisting_paths_of_delusion", "collapsed_observatory")
 *
 * ### Example Names
 * - "the_clockwork_labyrinth_of_cogs"
 * - "the_starlit_amphitheater_of_dreams"
 * - "the_primal_breeding_grounds"
 *
 * @since 0.1.0
 */
val NAMES_OF_ARENA_MAPS by lazy {
  arrayOf(
    "the_forgotten_city_of_ice",
    "the_burning_desert_of_fire",
    "the_hidden_caverns_of_shadows",
    "the_eternal_storm_plains",
    "the_crystallized_mountains",
    "the_lost_temple_of_wind",
    "the_abyssal_trench",
    "the_enchanted_forest_of_eternity",
    "the_volcanic_crater_of_doom",
    "the_frozen_wasteland",
    "the_golden_kingdom_of_sun",
    "the_mystic_river_of_dreams",
    "the_ancient_ruins_of_time",
    "the_celestial_arena_of_stars",
    "the_dark_citadel_of_night",
    "the_serene_garden_of_peace",
    "the_chaotic_realm_of_void",
    "the_legendary_battlefield",
    "the_cursed_swamp_of_sorrow",
    "the_sky_islands_of_eternity",
    "the_sunken_kingdom_of_the_deep",
    "the_whispering_corridors_of_time",
    "the_volcanic_heart_of_destruction",
    "the_celestial_observatory_of_fate",
    "the_haunted_catacombs_of_souls",
    "the_twisting_paths_of_delusion",
    "the_glimmering_oasis_of_mirage",
    "the_shattered_monoliths_of_creation",
    "the_eternal_battlefield_of_legends",
    "the_forbidden_archive_of_secrets",
    "the_clockwork_labyrinth_of_cogs",
    "the_bloodstone_caverns_of_anguish",
    "the_overgrown_sanctuary_of_life",
    "the_fractured_dimension_of_chaos",
    "the_silent_abyss_of_darkness",
    "the_gilded_palace_of_avarice",
    "the_weeping_chapel_of_lament",
    "the_blazing_foundry_of_industry",
    "the_crimson_reef_of_corals",
    "the_umbral_stronghold_of_shadows",
    "the_starlit_amphitheater_of_dreams",
    "the_primordial_jungle_of_beasts",
    "the_collapsed_observatory_of_stars",
    "the_singing_dunes_of_eternity",
    "the_overgrown_citadel_of_ivy",
    "the_mechanical_heart_of_industry",
    "the_sacrificial_altar_of_gods",
    "the_forsaken_graveyard_of_titans",
    "the_floating_archipelago_of_wonders",
    "the_blood_moon_courtyard",
    "the_echoing_halls_of_madness",
    "the_primal_breeding_grounds"
  )
}

/**
 * Predefined collection of player usernames for testing.
 *
 * Contains 50 gaming-style usernames generated by AI, featuring:
 * - Elemental and animal themes ("ShadowWolf", "IceQueen_7")
 * - Warrior archetypes ("DarkKnight_42", "LunarKnight")
 * - Fantasy roleplay elements ("MysticSoul", "NetherKing")
 *
 * ### Example Names
 * - "ThunderFox"
 * - "CrystalKnight"
 * - "PhoenixRise"
 *
 * @since 0.1.0
 */
val NAMES_OF_USERS by lazy {
  arrayOf(
    "ShadowWolf",
    "IceQueen_7",
    "FireDragonX",
    "DarkKnight_42",
    "ThunderLord",
    "MysticSoul",
    "SkyHunter",
    "IronGiant_9",
    "GoldenEagle",
    "FrostByte_1",
    "EmeraldEyes",
    "NetherKing",
    "OceanMaster",
    "StormRider",
    "MoonWalker",
    "AncientSage",
    "CrystalWiz",
    "LavaPouncer",
    "SandStriker",
    "TimeTraveler",
    "BlazeRunner",
    "NightStalker",
    "PhoenixRise",
    "SteelFang_99",
    "AquaMage",
    "CrimsonKing",
    "FrostyFox",
    "ShadowBladeX",
    "IronClad_7",
    "SolarFlare",
    "WindWalker",
    "EchoHunter",
    "VoidWarden",
    "LunarKnight",
    "ThunderFox",
    "NeonSpecter",
    "RogueTiger",
    "MysticFlame",
    "StormChaser",
    "GoldenAxe_42",
    "DarkPhoenix",
    "IceWarrior",
    "FlameStrike",
    "SkyGuardian",
    "EarthShaker",
    "FrostWarden",
    "BlazeFury",
    "ShadowSoul",
    "IronWolf_13",
    "CrystalKnight"
  )
}

val NAMES_OF_TEAMS by lazy {
  arrayOf(
    "white",
    "orange",
    "magenta",
    "light_blue",
    "yellow",
    "lime",
    "pink",
    "gray",
    "light_gray",
    "cyan",
    "purple",
    "blue",
    "brown",
    "green",
    "red",
    "black"
  )
}

/**
 * @since 0.1.0
 */
val BUILTIN_COLORS: Map<String, String> by lazy {
  mapOf(
    "&0" to "#000000", // Black
    "&1" to "#0000AA", // Dark blue
    "&2" to "#00AA00", // Dark green
    "&3" to "#00AAAA", // Dark aqua
    "&4" to "#AA0000", // Dark red
    "&5" to "#AA00AA", // Purple
    "&6" to "#FFAA00", // Gold
    "&7" to "#AAAAAA", // Gray
    "&8" to "#555555", // Dark gray
    "&9" to "#5555FF", // Indigo
    "&a" to "#55FF55", // Bright Green
    "&b" to "#55FFFF", // Aqua
    "&c" to "#FF5555", // Red
    "&d" to "#FF55FF", // Pink
    "&e" to "#FFFF55", // Yellow
    "&f" to "#FFFFFF"  // White
  )
}