package me.kvdpxne.dtm.shared

import me.kvdpxne.dtm.configuration.Configuration

/**
 * Defines an object capable of sending messages to a performer.
 *
 * This interface provides methods for sending messages in various formats.
 */
interface Communicative {

  /**
   * Forces a message to be sent immediately to the performer.
   *
   * @param message The message to send.
   */
  fun sendMessage(message: String)

  /**
   * Sends a message to the performer if possible.
   *
   * The message is generated by the provided lambda function and sent using the
   * `sendMessage(String)` method.
   *
   * @param message A lambda function that returns the message to send.
   */
  fun sendMessage(message: () -> String) {
    this.sendMessage(message())
  }

  /**
   * Forces multiple messages to be sent to the performer.
   *
   * @param messages The messages to send.
   */
  fun sendMessages(vararg messages: String)

  fun sendMessages(messages: () -> Array<out String>) {
    this.sendMessages(*messages())
  }

  fun sendConfiguredMessage(servedMessage: (Configuration) -> String) {
    this.sendMessage(servedMessage(Configuration))
  }

  fun sendConfiguredMessages(servedMessages: (Configuration) -> Array<out String>) {
    this.sendMessages(*servedMessages(Configuration))
  }
}